# Generated by Django 4.2.3 on 2023-08-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                (
                    "base_zipcode",
                    models.CharField(max_length=5, verbose_name="USPS ZIP Code"),
                ),
                (
                    "plus4_zipcode",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="USPS ZIP+4"
                    ),
                ),
                ("comment", models.TextField()),
            ],
        ),
    ]
